name: trivy-security-scanning
on:
  push:
    branches: 
      - main
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  security-events: write # To upload sarif files

jobs:
  chart-test:
    name: chart-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: '${{ secrets.nourman_pat }}'

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
        id: install

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.4

      - name: Run Trivy vulnerability scanner dont have code scanning enabled
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: 'config'
          hide-progress: false
          output: trivy.txt

      - name: Publish Trivy Output to Summary
        run: |
          if [[ -s trivy.txt ]]; then
            {
              echo "### Security Output"
              echo "<details><summary>Click to expand</summary>"
              echo ""
              echo '```terraform'
              cat trivy.txt
              echo '```'
              echo "</details>"
            } >> $GITHUB_STEP_SUMMARY
          fi
