name: trivy-security-scanning
on:
  push:
    branches: 
      - main
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  security-events: write # To upload sarif files

jobs:
  chart-test:
    name: chart-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: '${{ secrets.nourman_pat }}'

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
        id: install

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.4

      - name: Run Trivy vulnerability scanner in IaC mode
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: 'config'
          hide-progress: false
          format: 'sarif'
          output: 'trivy-results.sarif'
          exit-code: '1'
          ignore-unfixed: true
          #severity: 'CRITICAL,HIGH'
          #scan-ref: 'charts/sample-helm-devsecops'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
